INVITE_CODE_PREFIX = "TYC-"
INVITE_CODE_SUFFIX_LENGTH = 4
INVITE_CODE_ALPHABET = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
INVITE_CODE_PATTERN = r"^TYC-[A-Z0-9]{4}$"

MAX_SESSION_MEMBERS = 8
SESSION_INVITE_CODE_MAX_RETRIES = 5

WS_SEND_QUEUE_MAX_SIZE = 256
WS_HEARTBEAT_INTERVAL_S = 20
WS_HEARTBEAT_TIMEOUT_S = 25
WS_PROTOCOL_VERSION = 1
# Grace before a disconnected member is removed from a waiting room (transient-drop tolerant).
WS_DISCONNECT_GRACE_S = 15

# Stickers are served from the FE under /stickers/<pack>/<file>.
STICKER_URL_PATTERN = r"^/stickers/[\w-]+/[\w.-]+$"
